### ISSUE TITLE
Fatal Error after Installation

### ISSUE THREAD

**Issue by Zeromax** [contao/standard-edition#36]
After Installation on WIndows via composer I have a Message under the "Installation not complete screen"

```
Fatal error: Uncaught exception 'RuntimeException' with message 
'Failed to start the session because headers have already been sent
by "D:\www\contao-4-test\www\app\bootstrap.php.cache" at line 1502.' 
in D:\www\contao-4-test\www\app\cache\prod\classes.php:114 

Stack trace:
#0 D:\www\contao-4-test\www\app\cache\prod\classes.php(188): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start()
#1 D:\www\contao-4-test\www\app\cache\prod\classes.php(561): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('contao_frontend')
#2 D:\www\contao-4-test\www\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Session.php(78): Symfony\Component\HttpFoundation\Session\Session->getBag('contao_frontend') 
#3 D:\www\contao-4-test\www\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Session.php(97): Contao\Session->__construct()
#4 [internal function]: Contao\Session::getInstance() 
#5 D:\www\contao-4-test\www\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Sy in D:\www\contao-4-test\www\app\bootstrap.php.cache on line 3188
```

**Comment by leofeyer** [comment]
Did you use `composer create-project`? Which version did you install?

**Comment by Zeromax** [comment]
Yes. I Contao 4.1.1 latest version.

>  composer create-project contao/standard-edition contao-4

Just tested it again (empty DB, delete the whole contao4 Folder)

Now I have Contao 4.1.2

```
( ! ) Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to start the session because headers have already been sent by "D:\www\contao-4-test\www\app\bootstrap.php.cache" at line 1502.' in D:\www\contao-4-test\www\app\bootstrap.php.cache on line 3188
( ! ) RuntimeException: Failed to start the session because headers have already been sent by "D:\www\contao-4-test\www\app\bootstrap.php.cache" at line 1502. in D:\www\contao-4-test\www\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php on line 140
Call Stack
#   Time    Memory  Function    Location
1   0.0004  136520  {main}( )   ...\app.php:0
2   0.4801  6766240 Symfony\Component\HttpKernel\HttpCache\HttpCache->terminate( )  ...\app.php:28
3   0.4801  6766288 Symfony\Component\HttpKernel\Kernel->terminate( )   ...\HttpCache.php:242
4   0.4801  6766328 Symfony\Component\HttpKernel\HttpKernel->terminate( )   ...\bootstrap.php.cache:2491
5   0.4804  6772840 Symfony\Component\EventDispatcher\EventDispatcher->dispatch( )  ...\bootstrap.php.cache:3183
6   0.4810  6783552 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch( )    ...\EventDispatcher.php:46
7   0.4841  7211904 call_user_func:{D:\www\contao-4-test\www\vendor\symfony\symfony\src\Symfony\Component\EventDispatcher\EventDispatcher.php:181} ( )  ...\EventDispatcher.php:181
8   0.4841  7212000 Contao\CoreBundle\EventListener\CommandSchedulerListener->onKernelTerminate( )  ...\EventDispatcher.php:181
9   0.4841  7212096 Contao\CoreBundle\Framework\ContaoFramework->createInstance( )  ...\CommandSchedulerListener.php:56
10  0.4848  7257448 newInstanceArgs ( ) ...\ContaoFramework.php:161
11  0.4848  7257536 Contao\FrontendCron->__construct( ) ...\ContaoFramework.php:161
12  0.4848  7257552 Contao\Frontend->__construct( ) ...\FrontendCron.php:29
13  0.4848  7257576 Contao\System->__construct( )   ...\Frontend.php:52
14  0.4848  7257904 Contao\System->import( )    ...\System.php:110
15  0.4854  7283680 call_user_func:{D:\www\contao-4-test\www\vendor\contao\core-bundle\src\Resources\contao\library\Contao\System.php:163} ( )  ...\System.php:163
16  0.4854  7283720 Contao\Session::getInstance( )  ...\System.php:163
17  0.4854  7283888 Contao\Session->__construct( )  ...\Session.php:97
18  0.4855  7283936 Symfony\Component\HttpFoundation\Session\Session->getBag( ) ...\Session.php:78
19  0.4855  7283936 Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag( )    ...\Session.php:237
20  0.4855  7283936 Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start( ) ...\NativeSessionStorage.php:274
( ! ) LogicException: Request stack is empty in D:\www\contao-4-test\www\app\bootstrap.php.cache on line 3188
Call Stack
#   Time    Memory  Function    Location
1   0.4857  7312296 Symfony\Component\Debug\ErrorHandler->handleException( )    ...\ErrorHandler.php:0
2   0.4857  7326680 Symfony\Component\Debug\ErrorHandler->handleException( )    ...\ErrorHandler.php:591
```

**Comment by leofeyer** [comment]
I just tested in on Windows 10 and the installation worked like a charm.
