### ISSUE TITLE
Change /web to /public_html

### ISSUE THREAD

**Issue by t-me** [contao/standard-edition#51]
Hello All,

I want to change the "/web" directory to "/public_html".

When i follow this link : [symfony.com/override-the-web-directory](http://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-web-directory)

and do a composer update it looks fine. But when i go to install.php i get a error 500. in the log files i see this 

```
[Thu Jan 19 21:06:15.625264 2017] [lsapi:error] [pid 234676] [client 82.75.164.96:0] [host t-me.nl] Backend fatal error: PHP Fatal error:  Uncaught InvalidArgumentException: The target directory "/home/debxxx/domains/t-me.nl/app/../web" does not exist. in /home/debxxx/domains/t-me.nl/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php:85\nStack trace:\n#0 /home/debxxx/domains/t-me.nl/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(262): Symfony\\Bundle\\FrameworkBundle\\Command\\AssetsInstallCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))\n#1 /home/debxxx/domains/t-me.nl/vendor/contao/installation-bundle/src/Controller/InstallationController.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))\n#2 /home/debxxx/domains/t-me.nl/vendor/contao/installation-bundle/src/Controller/InstallationController.php(133): Contao\\InstallationBundle\\Controller\\InstallationController->runCommand(Object(Symfon in /home/debxxx/domains/t-me.nl/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/AssetsInstallCommand.php on line 85\n
```

The reason i want to change it is because i cant change public_html to web directory as root folder.

**Comment by ghost** [comment]
The issue has been moved to contao/installation-bundle#40.
