### ISSUE TITLE
Fehler beim Aufruf der Install.php - 4.3.6

### ISSUE THREAD

**Issue by Ainschy** [contao/standard-edition#56]
Ich konnte bisher erfolgreich die 4.3.4 / 4.3.5 als zip auf contao.org herunterladen, entpacken, die install.php aufrufen und durchführen. Abschließend dann Composer update (über ssh) ausgeführt.

Unter 4.3.6 kann ich die install.php nicht mehr aufrufen.

PHP 5.6.29 CGI

```
Catchable fatal error: Argument 1 passed to Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider::__construct() must be an instance of Contao\CoreBundle\Framework\ContaoFrameworkInterface, instance of Symfony\Component\DependencyInjection\ContainerBuilder given, called in /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/installation-bundle/src/DependencyInjection/ContainerFactory.php on line 174 and defined in /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php on line 43
```

PHP 7.1.1 CGI

```
Fatal error: Uncaught TypeError: Argument 1 passed to Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider::__construct() must be an instance of Contao\CoreBundle\Framework\ContaoFrameworkInterface, instance of Symfony\Component\DependencyInjection\ContainerBuilder given, called in /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/installation-bundle/src/DependencyInjection/ContainerFactory.php on line 174 and defined in /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:43 Stack trace: #0 /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/installation-bundle/src/DependencyInjection/ContainerFactory.php(174): Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->__construct(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/installation-bundle/src/HttpKernel/InstallationKernel.php(109): Contao\InstallationBundle\DependencyInjection\ContainerFactory::create(Object(Contao\Instal in /www/htdocs/xxxxxxxxx/webseiten/contao-4.3.6/vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php on line 43`
```

Hosting ist bei all-inkl.com, Paket: Premium (mit ssh)

**Comment by aschempp** [comment]
Did you delete all existing caches?

**Comment by leofeyer** [comment]
Gibt mal anstatt `install.php` direkt `/contao/install` ein.

**Comment by Ainschy** [comment]
Danke Leo, mit `/contao/install` klappt es!

@aschempp ist eine frische Installation

**Comment by leofeyer** [comment]
In Contao 4.4 wird `install.php` auch nur noch auf `/contao/install` weiterleiten, insofern kannst Du Dir das schon mal merken. 😄 

Behoben in contao/installation-bundle@758fc493f8f8796532595b7c799113950f18c8e4.
