### ISSUE TITLE
Fehler nach Installation unter XAMPP

### ISSUE THREAD

**Issue by markocupic** [contao/standard-edition#63]
Fehler nach Installation unter Windows 10 und xampp beim Aufrufen von install.php:
contao/contao-standard und symphony 3.2.6

```
Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "event_dispatcher".' in C:\xampp\htdocs\contao\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:795 Stack trace: #0 C:\xampp\htdocs\contao\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php(431): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('event_dispatche...') #1 C:\xampp\htdocs\contao\vendor\contao\installation-bundle\src\Controller\InstallationController.php(125): Symfony\Component\DependencyInjection\ContainerBuilder->get('event_dispatche...') #2 C:\xampp\htdocs\contao\vendor\contao\installation-bundle\src\Controller\InstallationController.php(63): Contao\InstallationBundle\Controller\InstallationController->initializeApplication() #3 C:\xampp\htdocs\contao\vendor\contao\installation-bundle\src\HttpKernel\InstallationKernel.php(89): Contao\InstallationBundle\Con in C:\xampp\htdocs\contao\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php on line 795
```

**Comment by xchs** [comment]
See https://github.com/contao/managed-edition/issues/7

You have to run the Contao install tool with the `/contao/install` entry point.

**Comment by markocupic** [comment]
When I'm downloading Contao 4.3.9  from contao.org and then run the install tool with /contao/install this error message appears:
```
ERROR   system/themes/flexible   The path "system/themes/flexible" exists and is not a symlink.  
ERROR   web/assets               The path "web/assets" exists and is not a symlink.              
ERROR   web/system/themes        The path "web/system/themes" exists and is not a symlink.       
ERROR   system/logs              The path "system/logs" exists and is not a symlink.    
```

**Comment by markocupic** [comment]
Don't ask me why! But when I'm reloading the page 5-7 times the error message disappears.
